---
- name: Nutanix Cluster Shutdown Process
  hosts: localhost
  tasks:
   
       # Stop the Stop Prism Central (requires modified cluster command to allow no prompt)
    - name: Stop Prism Central services
      shell: |
        sshpass -p "nutanix/4u" ssh -o StrictHostKeyChecking=no nutanix@192.168.1.242 "/home/nutanix/stop.sh"
      ignore_errors: yes
      
          # Wait 10 seconds for Prism Central processes to stop
    - name: Wait for 10 seconds for PC processes to stop
      pause:
        seconds: 60
      
   # Shutdown all VMs on the cluster
    - name: Initiate ACPI shutdown for all VMs
      shell: |
        sshpass -p "nutanix/4u" ssh -o StrictHostKeyChecking=no nutanix@192.168.1.184 "/usr/local/nutanix/bin/acli vm.shutdown '*'"
      ignore_errors: yes

    # Optional: Wait for 60 seconds to ensure VMs are shut down
    - name: Wait for 60 seconds for VMs to shut down
      pause:
        seconds: 60

   # Shutdown all VMs on the cluster
    - name: Force power off remaining VMs
      shell: |
        sshpass -p "nutanix/4u" ssh -o StrictHostKeyChecking=no nutanix@192.168.1.184 "/usr/local/nutanix/bin/acli vm.off '*'"
      ignore_errors: yes

    # Step 5: Stop the Nutanix Cluster (requires modified cluster command to allow no prompt)
    - name: Stop the cluster
      shell: |
        sshpass -p "nutanix/4u" ssh -o StrictHostKeyChecking=no nutanix@192.168.1.184 "/home/nutanix/stop.sh"
      ignore_errors: yes

    # Step 6: Shutdown the CVMs
    - name: Shutdown CVM on Node 1
      shell: |
        sshpass -p "nutanix/4u" ssh -o StrictHostKeyChecking=no nutanix@192.168.1.184 "sudo shutdown -h now"
      ignore_errors: yes
      no_log: yes

    - name: Shutdown CVM on Node 2
      shell: |
        sshpass -p "nutanix/4u" ssh -o StrictHostKeyChecking=no nutanix@192.168.1.185 "sudo shutdown -h now"
      ignore_errors: yes
      no_log: yes

    - name: Shutdown CVM on Node 3
      shell: |
        sshpass -p "nutanix/4u" ssh -o StrictHostKeyChecking=no nutanix@192.168.1.186 "sudo shutdown -h now"
      ignore_errors: yes
      no_log: yes

    # Optional: Wait for 30 seconds after CVMs shutdown
    - name: Wait for 30 seconds after shutting down CVMs
      pause:
        seconds: 30

    # Step 7: SSH to AHV Hosts and issue shutdown
    - name: Shutdown AHV Host on Node 1
      shell: |
        sshpass -p "nutanix/4u" ssh -o StrictHostKeyChecking=no root@192.168.1.180 "shutdown -h now"
      ignore_errors: yes
      no_log: yes

    - name: Shutdown AHV Host on Node 2
      shell: |
        sshpass -p "nutanix/4u" ssh -o StrictHostKeyChecking=no root@192.168.1.181 "shutdown -h now"
      ignore_errors: yes
      no_log: yes

    - name: Shutdown AHV Host on Node 3
      shell: |
        sshpass -p "nutanix/4u" ssh -o StrictHostKeyChecking=no root@192.168.1.182 "shutdown -h now"
      ignore_errors: yes
      no_log: yes